language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./_script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
    - ci
    - master
    - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
#    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
     - NOKOGIRI_USE_SYSTEM_LIBRARIES=false

notifications:
  email:
    on_success: change
    on_failure: always
