# Site settings
title: CC†
email: c@rezometz.org
description: > # this means to ignore newlines until "baseurl:"
    La Communauté Chrétienne de CentraleSupélec à Metz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cccroix.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: cccroix
github_repo: cccroix.github.io
paginate: 10
paginate_path: "/page:num/"

default_text: "---%0Alayout:%20post%0Atitle:%20Mon%20titre%0Aauthor:%20alias%0Adate:%20AAAA-MM-JJ%20HH:MM:SS%20CET%0Acategories:%20nouvelles%0A---%0A%0A%23%20Mon%20sous-titre%0A"

collections:
 eglises:
   output: true

# Build settings
markdown: kramdown
