# Site settings
title: CC†
email: c@rezometz.org
description: > # this means to ignore newlines until "baseurl:"
    La Communauté Chrétienne de CentraleSupélec à Metz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cccroix.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: cccroix
paginate: 20

# Build settings
markdown: kramdown
